name: Sync Dashboard to Next.js Repo

on:
  push:
    branches: [main]  # Adjust if your default branch is not `main`
    paths:
      - 'migration-analysis/notebooks/migrationDashboard.js'

jobs:
  push-dashboard:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Observable Repo
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"

      - name: Clone Next.js Repo
        run: |
          git clone https://x-access-token:${{ secrets.NEXTJS_REPO_TOKEN }}@github.com/kennonstewart/ssl-site.git ssl-site
          cd ssl-site
          git checkout -b auto/dashboard-update || git checkout auto/dashboard-update

      - name: Copy Dashboard File
        run: |
          cp migration-analysis/notebooks/migrationDashboard.js ssl-site/observable-notebooks/

      - name: Commit + Push Changes (Force Merge)
        run: |
          cd ssl-site
          git add observable-notebooks/migrationDashboard.js
          git commit -m "chore: sync updated dashboard module from Observable" || echo "No changes to commit"
          git pull --rebase origin auto/dashboard-update || git rebase --skip
          git push -f origin auto/dashboard-update || echo "Push failed, manual intervention required"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.NEXTJS_REPO_TOKEN }}
          path: ssl-site/observable-notebooks/migrationDashboard.js
          branch: auto/dashboard-update
          title: "Update migration dashboard"
          body: "This PR syncs the latest build of the Observable dashboard module."
